name: wesolve
description: "Service distribution application"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# --------------------- PACKAGES ---------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^0.13.6
  intl: ^0.19.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  logger: ^2.2.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.0.1
  cached_network_image: ^3.3.1
  wakelock_plus: ^1.1.4
  flutter_paypal_checkout: ^1.0.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

  # ./ --------------------- PACKAGES END --------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # --------------------- LOCAL ASSETS --------------------- #
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

    # --------------------- GOOGLE FONTS --------------------- #
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
    - family: Antonio
      fonts:
        - asset: assets/fonts/Antonio-Bold.ttf
          weight: 700